arXiv/arxiv-submission-ui

- submit/controllers/authorship.py
- submit/controllers/policy.py
- submit/routes/ui.py
- submit/templates/submit/policy.html
This PR creates the form field for policy acknowledgement and adds a simple yes/no verification on the field, raising an error in the event that the box is not checked.  Pretty sure this is in line with the state of where the previous pages are.  Some of this was done a bit blindly -- followed the pattern for event creation from authorship and verify_user.
Note: I noticed that the handy progress bar links aren't going to work any more due to not having submission_id passed and also we don't want to have the skip forward...took a short stab at how that might work but ended up aborting the effort for now. It's a separate task from this PR and possibly out of scope for the sprint.
> ARXIVNG-875 add form field and validation for policy acknowledgement

- .coveragerc
- Pipfile
- Pipfile.lock
- submit/controllers/authorship.py
- submit/controllers/license.py
- submit/controllers/policy.py
- submit/controllers/tests/__init__.py
- submit/controllers/tests/test_authorship.py
- submit/controllers/tests/test_license.py
- submit/controllers/tests/test_policy.py
- submit/controllers/tests/test_verify_user.py
- submit/controllers/util.py
- submit/controllers/verify_user.py
- submit/routes/ui.py
- submit/templates/submit/authorship.html
- submit/templates/submit/base.html
- submit/templates/submit/license.html
- submit/templates/submit/policy.html
- submit/templates/submit/verify_user.html
This also contributes to ARXIVNG-911 by changing the form request method on verify_user to POST.
The basic idea is that we are catching ``InvalidStack``, and displaying the exception messages on its constituent ``InvalidEvent``s at the top of the page. Here's a mockup (not real exceptions):
In addition, we should leverage the event's own validation on the form. Will do this next.
> ARXIVNG-897 added InvalidStack handling to verify_user controller, and tests

- Pipfile
- Pipfile.lock
- submit/controllers/__init__.py
- submit/controllers/authorship.py
- submit/controllers/classification.py
- submit/controllers/tests/test_classification.py
- submit/controllers/tests/test_primary.py
- submit/controllers/util.py
- submit/routes/ui.py
- submit/static/css/submit.css
- submit/static/sass/submit.sass
- submit/templates/submit/classification.html
- submit/templates/submit/cross_list.html
- submit/templates/submit/submit_macros.html
- submit/tests/__init__.py
This adds cross-list functionality to the submission UI. Things that this PR does now:
- Allows the user to add and remove cross-list categories. Note that:
- If a primary is selected, it will not show up in the drop-down for secondaries; 
- A given category cannot be added twice; 
- Selected secondaries do not appear as options for primary (if the user goes back).
- Catches up on type annotations and some minor docstyle issues.
Things that this feature does not do:
- Limit option to endorsed/preferred categories (out of scope)
- Address accessibility issue around optgroup font weight (let's address with filtering)
**Note**: In this implementation, if the user has selected a category but has **not** clicked the "add" button, I am not saving the result on previous/next. This seemed the …
> ARXIVNG-877 add cross-list functionality (secondary classification)

- Pipfile
- Pipfile.lock
- submit/controllers/__init__.py
- submit/controllers/metadata.py
- submit/controllers/tests/test_metadata.py
- submit/controllers/util.py
- submit/routes/ui.py
- submit/templates/submit/add_metadata.html
- submit/templates/submit/add_optional_metadata.html
This delivers the core and optional metadata controllers. I also spent some time working on a more convenient integration with the core events package. The upshot is that we want to leverage the core events validation for validating data on the form. If this looks like a promising direction, I'll refactor the other controllers to use this pattern.
Would like to merge this by noon tomorrow (Friday), if possible. You'll have to manually skip over to step 9 when testing.
> ARXIVNG-878 core and optional metadata

- submit/routes/ui.py
- submit/templates/submit/base.html
- submit/templates/submit/confirm_delete.html
Simple template to implement confirmation dialog screen.
Buttons are written as links rather than form elements; assumed we didn't need a form for a yes/no confirmation but I may be mistaken?
> ARXIVNG-989: delete files template

- Pipfile
- Pipfile.lock
- submit/controllers/metadata.py
- submit/static/css/submit.css
- submit/static/css/submit.css.map
- submit/static/sass/submit.sass
- submit/templates/submit/add_metadata.html
- submit/templates/submit/add_optional_metadata.html
- submit/templates/submit/authorship.html
- submit/templates/submit/classification.html
- submit/templates/submit/cross_list.html
- submit/templates/submit/file_process.html
- submit/templates/submit/license.html
- submit/templates/submit/verify_user.html
Changes made in pursuit of correcting all of the language that was identified in the usability study:
- Proxy (removed from title on authorship page)
- Forename/surname (changed to "First or Given"/"Last or Family" on verify_user and add_metadata pages)
- Primary compiler (removed "primary"), and I expect this page will change further when we actually do the UI for compilation service integration
- Archives (mentioned in an info box on the Classification page, changed to "categories")
- Cross-list (added info link)
- Box on cross-list page labeled with "Secondary Categories"
Opportunistic layout, accessibility, and spacing edits were also made. Incomplete, but better. Will continue to make incremental improvements in this manner.
Labels on metadata page were moved to above the input …
> ARXIVNG-985 change labels with confusing terms; ARXIVNG-987 label box for Selected Categories

- submit/controllers/tests/test_upload.py
- submit/controllers/upload.py
- submit/factory.py
- submit/filters.py
- submit/services/filemanager.py
- submit/templates/submit/file_upload.html
This works by comparing the modified timestamp of the file to the current time. If the difference is less than two seconds (configurable), we highlight the file. This way we get a nice visual confirmation when the file is first uploaded, but the green won't stick around on subsequent reloads of the page.
Note that this assumes that timestamps from the file management service are localized. In the current develop branch of FM, this is not the case. Will fix that shortly.
> ARXIVNG-1135 highlight files that were just uploaded 

- submit/controllers/tests/test_upload.py
- submit/controllers/upload.py
- submit/services/filemanager.py
- submit/templates/submit/file_upload.html
This adds support on the submission UI to upload files as ancillary files. Instead of placing the file in the root of the upload workspace, files should be placed in the ancillary subdirectory (``anc``). This depends on https://github.com/cul-it/arxiv-filemanager/pull/20 and on https://github.com/cul-it/arxiv-submission-ui/pull/31
> ARXIVNG-1175 Support for ancillary uploads

- Pipfile
- Pipfile.lock
- submit/config.py
- submit/templates/submit/authorship.html
- submit/templates/submit/cross_list.html
- submit/templates/submit/file_upload.html
- submit/templates/submit/license.html
Most of ARXIVNG-1270 was done along with ARXIVNG-1259; this PR cleans up some of the leftovers in file upload help text. Imperfect but better.
I chose to place these particular URLs in the submit repo directly because they seemed to apply only within the submission process; happy to move them to base if they are deemed more general.
Screenshot of the new help info for file upload:
> ARXIVNG-1215 ARXIVNG-1270 configure URLs, add help info

- Pipfile
- Pipfile.lock
- submit/controllers/__init__.py
- submit/controllers/authorship.py
- submit/controllers/classification.py
- submit/controllers/jref.py
- submit/controllers/license.py
- submit/controllers/metadata.py
- submit/controllers/policy.py
- submit/controllers/tests/test_jref.py
- submit/controllers/upload.py
- submit/controllers/verify_user.py
- submit/routes/auth.py
- submit/routes/ui.py
- submit/routes/util.py
- submit/templates/submit/base.html
- submit/templates/submit/jref.html
- submit/templates/submit/status.html
- submit/tests/test_workflow.py
- submit/util.py
This leverages some refactoring in submission-core. This needs massive styling help, copy, etc. Mostly a conversation-starter. What should this look like?
Here's roughly how JREFs work in classic: a submission is published, and then a user wants to add a DOI or something. So they submit a pared-down submission that just updates DOI, journal ref, and/or report num. This works its way through the system, and the abs file eventually gets updated. The version number doesn't get changed.
Here's roughly how JREFs work in submission core: a submission is published, and then a user wants to add a DOI or something. We create SetDOI, SetJournalReference, and/or SetReportNum command(s). Right now this integrates with classic to create those pared down submissions in the database. Later on, we'll …
> ARXIVNG-1343 first pass at JREF submission

- Pipfile
- Pipfile.lock
- submit/controllers/__init__.py
- submit/controllers/authorship.py
- submit/controllers/classification.py
- submit/controllers/jref.py
- submit/controllers/license.py
- submit/controllers/metadata.py
- submit/controllers/policy.py
- submit/controllers/tests/test_jref.py
- submit/controllers/upload.py
- submit/controllers/verify_user.py
- submit/controllers/withdraw.py
- submit/routes/auth.py
- submit/routes/ui.py
- submit/routes/util.py
- submit/templates/submit/base.html
- submit/templates/submit/jref.html
- submit/templates/submit/status.html
- submit/templates/submit/withdraw.html
- submit/tests/test_workflow.py
- submit/util.py
This works a lot like the JREF functionality, and actually I branched from #42 so you'll see those changes in here as well. Like the JREF, withdrawals only apply to published papers. So you'll want to go to the temporary status endpoint (``/{submission id}``), click the "publish..." button, and then visit ``/{submission id}/withdraw``. 
Note that this only works once for a submission; you'll get an error if you try a second time, which is just because I didn't make the temporary "publish" functionality very robust.
Here's what you'll see when you go to the withdrawal request page:
Here's what you see when you click "Proceed":
Note that, like in #42, we still need the abs-page preview. In this case, we'll add the reason for the withdrawal to the "comments" field (integration with classic).
> ARXIVNG-1341 Added withdrawal request 

- submit/config.py
- submit/controllers/withdraw.py
- submit/templates/submit/jref.html
- submit/templates/submit/withdraw.html
- submit/tests/test_workflow.py
Carried over layout and text suggestions from ARXIVNG-1341.
Accessibility scan using WAVE is clean.
> ARXIVNG-1396 update text and display for withdrawal template

- Pipfile
- Pipfile.lock
- submit/controllers/__init__.py
- submit/controllers/classification.py
- submit/controllers/cross.py
- submit/controllers/util.py
- submit/factory.py
- submit/filters.py
- submit/routes/ui.py
- submit/templates/submit/create.html
- submit/templates/submit/cross_list.html
- submit/templates/submit/request_cross_list.html
- submit/templates/submit/withdraw.html
- submit/util.py
This introduces support for cross-list requests. This is a little different from adding cross-list categories during a new or replacement submission. What we're doing here is creating a new request (on the submission as ``Submission.user_requests: List[UserRequest]``) with a set of additional cross-list categories that the user would like added to an existing version.
Here's an example with a new submission that I started (got through classification steps), and then used the ``/{submission_id}/publish`` shortcut to artificially "publish" it.
The template needs a little work (looking for your direction @eawoods), but here's what the cross-list view looks like at the beginning. 
You can select a category that is not already on the submission, and add it to the request.
You can add a bunch. …
> ARXIVNG-1408 cross-list support

- submit/templates/submit/file_upload.html
I combined all the TeX-related notices into one box.
Jim - including you as a reminder to myself to ping you on this and future notices that are largely UI-communication related (almost all my contributions in the next couple of weeks will be). I think you've seen this particular screen in exactly the same state on Friday - one last look before it gets incorporated? I was thinking it might be good to have a quick review on help text as we go in these last few weeks to alpha. If you'd rather look at things all at once rather than in separate features let me know, we can work out a different review setup.
David and Jaimie - this screen is the only code change for this PR, just the blue box underneath the file upload form. No need to spin up the app to review.
> ARXIVNG-1371 Notify submitter that TeX source will be made public

- submit/config.py
- submit/controllers/classification.py
- submit/controllers/verify_user.py
- submit/routes/ui.py
- submit/templates/submit/classification.html
- submit/templates/submit/verify_user.html
I added a little Jinja filter that checks the number of endorsements against the list of currently active categories. Currently a little tricky to test, since it's hard to generate test users with endorsements that match all/none conditions.
The verify-user step displays a notice if a submitter doesn't have auto endorsements. It's a warning for "Some" and a danger for "None". Outstanding task: gatekeeping/validation on this stage for endorsement status "None".
---
Then, the classification step shows messages dependent on that endorsement status. It shows just the "Favorites" box for endorsements = all.
> ARXIVNG-1364 Make endorsement status clear to submitter early in process

- Pipfile
- Pipfile.lock
- submit/controllers/withdraw.py
- submit/routes/auth.py
- submit/templates/submit/final_preview.html
- submit/templates/submit/jref.html
- submit/templates/submit/withdraw.html
- submit/util.py
Here's what it looks like on the withdrawal page:
Here's what it looks like on the JREF page:
It's all wired up on the final preview page, but we can't see that yet...
Looking for any major show-stopper at this point. We'll need to re-verify this feature once the rest of the workflow is up and running. Hope to merge tomorrow (Dec 19) barring any blocking problems.
> ARXIVNG-1369 adding abs preview

- Pipfile
- Pipfile.lock
- README.md
- submit/controllers/classification.py
- submit/controllers/create.py
- submit/controllers/tests/test_authorship.py
- submit/controllers/tests/test_classification.py
- submit/controllers/tests/test_jref.py
- submit/controllers/tests/test_license.py
- submit/controllers/tests/test_metadata.py
- submit/controllers/tests/test_policy.py
- submit/controllers/tests/test_primary.py
- submit/controllers/tests/test_upload.py
- submit/controllers/tests/test_verify_user.py
- submit/controllers/util.py
- submit/domain.py
- submit/routes/ui.py
- submit/templates/submit/classification.html
- submit/templates/submit/verify_user.html
- submit/tests/test_workflow.py
This leverages https://github.com/arXiv/arxiv-auth/pull/30 (ARXIVNG-1468) to display the submitter's  endorsement status more coherently on the verify user page. 
Note that https://github.com/arXiv/arxiv-auth/blob/develop/generate_token.py can be used to generate auth tokens with different endorsement authorizations.
No endorsements:
Some endorsed categories:
``astro-ph.CO,astro-ph.GA``
Endorsed for entire archives (all categories in an archive):
``hep-ph.*,nucl-th.*,math-ph.*,physics.*,q-bio.*,nlin.*,hep-th.*``
*note that the ``.*`` after the archive keys is removed in https://github.com/arXiv/arxiv-base/pull/92*
Endorsed for everything (``*.*``):
> ARXIVNG-1451 ARXIVNG-1423 submitter endorsement display on verify user step

- Pipfile
- Pipfile.lock
- app.py
- bootstrap.py
- docker-compose.yml
- submit/controllers/cross.py
- submit/controllers/delete.py
- submit/controllers/jref.py
- submit/controllers/metadata.py
- submit/controllers/tests/test_classification.py
- submit/controllers/tests/test_jref.py
- submit/controllers/tests/test_primary.py
- submit/controllers/tests/test_upload.py
- submit/controllers/upload.py
- submit/controllers/withdraw.py
- submit/domain/__init__.py
- submit/flow_control.py
- submit/routes/ui.py
- submit/services/filemanager.py
- submit/services/tests/test_filemanager_integration.py
- submit/templates/submit/confirm_cancel_request.html
- submit/templates/submit/confirm_delete_submission.html
- submit/templates/submit/create.html
- submit/templates/submit/jref.html
- submit/templates/submit/status.html
- submit/templates/submit/withdraw.html
- submit/tests/test_workflow.py
- submit/util.py
- uwsgi.ini
Tweaked the slug when there is an open cross-list or withdrawal request:
Clicking the trash-can asks for confirmation:
et voila!
> ARXIVNG-1804 ability to cancel withdrawal and cross-list requests

- submit/routes/ui.py
basically just that; doesn't impact anything on our end, and makes it a little more convenient for users on systems that care about such things
> ARXIVNG-1017 add dot-three to PDF preview route

- submit/config.py
- submit/templates/submit/file_process.html
Straightforward and simple - adds `/help/faq/mistakes` and `/help/faq/texprobs` to config.py and links to the appropriate place:
Completed With Warnings gets a link to `texprobs`
Processing Failed gets a link to `mistakes`
Wasn't able to generate a screenshot for "Completed With Warnings", but noticed that we didn't have a view-PDF link (in theory, the PDF does get generated but we expect that it has rendering issues...right?). Added that plus the button-styled link for TeX rendering problems.
> ARXIVNG-1365 add links to tex help

- submit/templates/submit/add_metadata.html
- submit/templates/submit/add_optional_metadata.html
Erick: once this is merged, I'll be done poking at submissionUI until you give the OK. 
Review for code and content. Wasn't quite sure what to put in the bubbles, they're all a little bit lame in the "click for help" language.
I added the help message about having a jref option on the optional metadata page, too - felt like that note was missing.
As mentioned in Slack, we'll need an edited docs page for the help on metadata. I can get it started by cloning the /help/metadata page? Am guessing that the content can stay the same except for the technical-support part of what input can be accepted.
> ARXIVNG-2034 add metadata help bubbles

- submit/static/css/submit.css
- submit/static/sass/submit.sass
Trivial one line change to remove extra space in color specification. Font color for the fatal class is now white.
> Fix background color for fatal class.

- submit/templates/submit/admin_macros.html
Adds the LAYOUT only (no functionality) for admin functions.
In order to use the switch styling, arxiv-base will need to be updated with the inclusion of https://github.com/arXiv/arxiv-base/pull/126. The layout doesn't get super broken without it, you'll just see a simple checkbox instead of a switch.
(Note that white background buttons are tricky without losing the overlay, so I bailed on that idea and let them be transparent-background instead.)
> ARXIVNG-2031 add layout template for admin functions
